INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Single', 1, 1);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Single', 1, 2);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Single', 1, 3);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Single', 1, 4);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Single', 2, 1);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Single', 2, 2);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Double', 2, 3);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Triple', 2, 4);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Single', 3, 1);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Double', 3, 2);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Triple', 3, 3);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Triple', 3, 4);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Suite', 4, 1);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Suite', 4, 2);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Suite', 4, 3);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('Suite', 4, 4);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('President Suite', 5, 1);
INSERT INTO ROOM (TYPE, FLOOR, ROOM_NUMBER) VALUES ('President Suite', 5, 2);


INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Adams', 'Roy', 'radams1v@xinhuanet.com', 'United States', '1-(235)314-9823');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Adams', 'Martin', 'madams2b@msu.edu', 'China', '9-(401)660-9813');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Alvarez', 'Roger', 'ralvarezk@blogs.com', 'United States', '6-(980)036-6105');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Alvarez', 'Anne', 'aalvarez1y@mlb.com', 'United States', '7-(967)349-7237');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Alvarez', 'Ann', 'aalvarez20@jalbum.net', 'Afghanistan', '7-(418)731-2327');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Anderson', 'Betty', 'banderson14@digg.com', 'United States', '1-(291)830-0405');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Anderson', 'Laura', 'landerson24@icio.us', 'United States', '3-(587)240-6409');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Armstrong', 'Christopher', 'carmstrong2p@cyberchimps.com', 'United States', '3-(411)160-3757');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Bell', 'David', 'dbell2l@wp.com', 'United States', '8-(035)412-4547');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Berry', 'Paula', 'pberry1z@admin.ch', 'China', '6-(195)796-7745');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Bishop', 'Dennis', 'dbishopo@xinhuanet.com', 'Armenia', '4-(871)489-3543');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Bishop', 'Carolyn', 'cbishopw@1688.com', 'Ukraine', '5-(795)729-5690');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Black', 'Harold', 'hblack2p@clickbank.net', 'Indonesia', '0-(378)142-3343');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Bowman', 'Jerry', 'jbowman1j@fotki.com', 'Indonesia', '9-(389)678-8585');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Bradley', 'Keith', 'kbradley1c@techcrunch.com', 'United States', '5-(780)609-5353');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Brooks', 'Samuel', 'sbrooks4@google.co.uk', 'United States', '5-(517)250-0437');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Bryant', 'Donald', 'dbryant1@cdbaby.com', 'South Korea', '5-(629)251-0019');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Burke', 'Tammy', 'tburke2a@theglobeandmail.com', 'Russia', '8-(710)063-1619');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Burns', 'Joe', 'jburns18@mail.ru', 'Russia', '3-(465)132-7455');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Campbell', 'Jessica', 'jcampbell2i@cpanel.net', 'United States', '0-(150)386-2177');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Campbell', 'Christopher', 'ccampbell2i@amazon.de', 'Russia', '5-(275)117-4811');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Carpenter', 'Pamela', 'pcarpenterj@china.com.cn', 'United States', '6-(268)816-2465');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Carpenter', 'Paul', 'pcarpenter28@dropbox.com', 'Philippines', '3-(561)990-7094');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Carter', 'Tammy', 'tcarter1j@washington.edu', 'United States', '7-(489)865-7002');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Carter', 'Paul', 'pcarter1z@cnet.com', 'United States', '3-(854)158-1783');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Chapman', 'Justin', 'jchapmans@aol.com', 'United States', '1-(910)152-0295');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Chapman', 'Margaret', 'mchapmanb@hud.gov', 'Canada', '1-(010)495-9996');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Clark', 'Bonnie', 'bclark6@bing.com', 'United States', '9-(524)812-6248');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Clark', 'Andrea', 'aclark2j@sphinn.com', 'United States', '1-(123)323-9494');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Coleman', 'Shirley', 'scoleman26@bizjournals.com', 'United States', '7-(798)598-1459');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Coleman', 'Angela', 'acoleman6@gmpg.org', 'Russia', '9-(959)063-5551');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Cox', 'Harold', 'hcox23@dyndns.org', 'France', '6-(983)957-3202');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Cruz', 'Alan', 'acruzj@marketwatch.com', 'China', '1-(003)990-0308');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Cunningham', 'Anna', 'acunningham2@yale.edu', 'China', '7-(769)474-5961');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Daniels', 'Robin', 'rdaniels2d@weebly.com', 'United States', '7-(116)447-5902');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Daniels', 'Phillip', 'pdaniels1y@hexun.com', 'Kazakhstan', '4-(029)713-9304');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Davis', 'Thomas', 'tdavis1h@globo.com', 'United States', '5-(778)054-9695');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Dean', 'Joe', 'jdeanp@vinaora.com', 'United States', '9-(625)975-9705');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Dean', 'Sara', 'sdean1t@unc.edu', 'Mexico', '7-(206)725-7117');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Dixon', 'Patricia', 'pdixon2m@biglobe.ne.jp', 'United States', '1-(159)384-4102');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Dixon', 'Cynthia', 'cdixon1e@vimeo.com', 'China', '6-(422)372-7084');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Dixon', 'Todd', 'tdixon2o@ed.gov', 'China', '0-(290)722-9657');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Elliott', 'David', 'delliottn@wsj.com', 'Russia', '4-(687)980-5138');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Elliott', 'Gregory', 'gelliott2f@exblog.jp', 'Indonesia', '2-(826)961-5278');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Ellis', 'James', 'jellisa@wordpress.com', 'United States', '9-(104)768-0365');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Ferguson', 'Russell', 'rferguson1b@uol.com.br', 'United States', '7-(498)208-8970');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Welch', 'Tina', 'twelch1u@yahoo.co.jp', 'United States', '1-(518)288-4237');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Welch', 'Rose', 'rwelchu@gnu.org', 'Serbia', '9-(271)628-1625');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Wheeler', 'Paula', 'pwheeler1s@mac.com', 'United States', '4-(874)769-0414');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Williams', 'Shawn', 'swilliamsc@joomla.org', 'United States', '4-(867)695-7864');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Williams', 'Harold', 'hwilliamsm@dion.ne.jp', 'Russia', '5-(250)547-3562');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Willis', 'Paul', 'pwillis12@e-recht24.de', 'United States', '7-(560)524-0255');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Wood', 'Jose', 'jwoodn@mtv.com', 'United States', '3-(322)044-6672');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Wood', 'Janet', 'jwood1k@goodreads.com', 'Ireland', '0-(943)656-4847');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Wright', 'Victor', 'vwright7@baidu.com', 'Ukraine', '0-(279)357-3386');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Wright', 'Kimberly', 'kwrightf@tinyurl.com', 'Brazil', '3-(288)433-6668');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Wright', 'Joan', 'jwright1q@phoca.cz', 'Moldova','7-(830)749-3794');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER) VALUES('Young', 'Judith', 'jyoung11@goodreads.com', 'United States', '9-(659)879-6466');

INSERT INTO RESERVATION
  (ROOM_ID, GUEST_ID, RES_DATE)
  VALUES (
    (SELECT ROOM_ID FROM ROOM WHERE FLOOR = 2 AND ROOM_NUMBER = 3),
    (SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = 'Young'),
    '2018-10-19'
  );

